[GEMINI]
API_KEY = "AIzaSyCwZKI0k0VDM0pQyn_T1AejpCcTEspnZEk"

[openai]
api_key = "your-openai-api-key-here"

[database]
# If you want to add database connectivity later
host = "localhost"
port = 5432
database = "trading_db"
username = "your-username"
password = "your-password"

[trading]
# Trading configuration
initial_capital = 100000
max_position_size = 0.1
risk_free_rate = 0.02

[api_keys]
# Additional API keys for data sources
alpha_vantage = "your-alpha-vantage-key"
polygon = "your-polygon-key"
finnhub = "your-finnhub-key"
